#!/usr/bin/env python3
"""
Main Pipeline Orchestrator for the OSINT & Threat Intel Project

This master script runs the entire local pipeline by executing each of the 15
feature scripts in a logical, sequential order. It simulates a workflow by
assuming each script will read the output files generated by previous steps.

To Run:
1. Ensure you have created and activated the master virtual environment.
   (e.g., `source master_venv/bin/activate`)
2. Run this script from the project's root directory:
   `python3 main_pipeline.py`
"""

import subprocess
import sys
import os
import json
from datetime import datetime
import time

# --- Pipeline Configuration ---
# This dictionary defines the sequence of operations. Each stage has:
# - name: A descriptive name for logging.
# - path: The relative path to the Python script to execute.
# - enabled: A flag to easily enable or disable a stage for testing.
# - description: Explains the role and I/O of the script.

PIPELINE_STAGES = [
    # --- STAGE 1: DATA COLLECTION ---
    {
        "name": "Feature 1: Tor Relay Enumeration",
        "path": "FEAT_1_TOR_RELAY/relay_enum.py",
        "enabled": True,
        "description": "Fetches active Tor relays. Independent step."
    },
    {
        "name": "Feature 2: Onion Domain Discovery",
        "path": "FEAT_2_ONION_CRAWL/onion_domain_discovery.py",
        "enabled": True,
        "description": "Crawls seed URLs to find new .onion domains."
    },
    {
        "name": "Feature 3: Marketplace Scraping",
        "path": "FEAT_3_MARKET_SCRAPE/marketplace_scraper.py",
        "enabled": True,
        "description": "Scrapes a target marketplace for listings. Primary data source for analysis."
    },
    {
        "name": "Feature 5: STIX/TAXII Feed Parsing",
        "path": "FEAT_5_STIX_TAXII/stix_taxii_parser.py",
        "enabled": True,
        "description": "Fetches and parses public threat intelligence feeds."
    },
    # --- STAGE 2: EXTRACTION & INITIAL ANALYSIS ---
    {
        "name": "Feature 6: IOC Extraction",
        "path": "FEAT_6_IOC_EXTRACT/ioc_extractor.py",
        "enabled": True,
        "description": "Extracts IOCs (IPs, domains, hashes) from the scraped marketplace data."
    },
    {
        "name": "Feature 7: Named Entity Recognition (NER)",
        "path": "FEAT_7_NER/ner_feature.py",
        "enabled": True,
        "description": "Extracts entities (People, Orgs) from scraped marketplace data."
    },
    {
        "name": "Feature 8: Hash Extraction & Analysis",
        "path": "FEAT_8_HASH_EXTRACT/hash_extractor.py",
        "enabled": True,
        "description": "Extracts hashes from scraped data and enriches them via VirusTotal."
    },
    {
        "name": "Feature 11: Handle Correlation",
        "path": "FEAT_11_HANDLE_CORR/handle_correlator.py",
        "enabled": True,
        "description": "Correlates vendor handles from scrapes against a known threat actor database."
    },
    # --- STAGE 3: ENRICHMENT & DEEPER ANALYSIS ---
    {
        "name": "Feature 4: API Enrichment",
        "path": "FEAT_4_API_ENRICH/api_enrichment.py",
        "enabled": True,
        "description": "Enriches IOCs gathered from Feature 6 with multiple external APIs."
    },
    {
        "name": "Feature 9: Infrastructure Mapping",
        "path": "FEAT_9_INFRA_MAP/infrastructure_mapper.py",
        "enabled": True,
        "description": "Performs deep analysis on IP addresses from the IOC extraction step."
    },
    {
        "name": "Feature 10: Geolocation Correlation",
        "path": "FEAT_10_GEO_CORR/geolocation_correlator.py",
        "enabled": True,
        "description": "Analyzes geographic patterns and risks of IPs from the IOC extraction step."
    },
    {
        "name": "Feature 12: Behavioral Analysis",
        "path": "FEAT_12_BEHAVIORAL_ANALYSIS/behavioral_analysis.py",
        "enabled": True,
        "description": "Analyzes scraped vendor posts for behavioral patterns and sentiment."
    },
    {
        "name": "Feature 13: Reputation Scoring",
        "path": "FEAT_13_REPUTATION_SCORING/reputation_scorer.py",
        "enabled": True,
        "description": "Calculates reputation scores for vendors found during scraping."
    },
    {
        "name": "Feature 14: MITRE ATT&CK Mapping",
        "path": "FEAT_14_MITRE_ATTACK/mitre_mapper.py",
        "enabled": True,
        "description": "Maps text content from scrapes to MITRE ATT&CK techniques."
    },
    {
        "name": "Feature 15: Affiliate Analysis",
        "path": "FEAT_15_AFFILIATE_ANALYSIS/affiliate_analysis.py",
        "enabled": True,
        "description": "Analyzes scraped posts for signs of RaaS and affiliate programs."
    }
]

def run_feature(stage_config: dict) -> bool:
    """Executes a single feature script as a subprocess."""
    script_path = stage_config["path"]
    print("-" * 80)
    print(f"▶️  RUNNING: {stage_config['name']}")
    print(f"   SCRIPT: {script_path}")
    
    if not os.path.exists(script_path):
        print(f"❌ ERROR: Script not found at '{script_path}'. Aborting pipeline.")
        return False

    try:
        # Ensure we run the script with the same Python interpreter that is running this pipeline
        python_executable = sys.executable
        
        # Execute the script, capturing its output
        result = subprocess.run(
            [python_executable, script_path],
            capture_output=True,
            text=True,
            check=True,  # This will raise an exception if the script returns a non-zero exit code
            encoding='utf-8'
        )
        
        # Display the last 10 lines of the script's output for a quick summary
        print("   --- Script Output (Last 10 Lines) ---")
        for line in result.stdout.strip().split('\n')[-10:]:
            print(f"   | {line}")
        print("   -----------------------------------")
        print(f"✅ SUCCESS: {stage_config['name']} completed.")
        return True

    except subprocess.CalledProcessError as e:
        print(f"❌ ERROR: Script '{script_path}' failed with exit code {e.returncode}.")
        print("   --- STDERR ---")
        print(e.stderr)
        print("   --------------")
        return False
    except Exception as e:
        print(f"❌ An unexpected error occurred while running '{script_path}': {e}")
        return False

def main():
    """Main pipeline execution function."""
    print("=" * 80)
    print("🚀 STARTING OSINT & THREAT INTELLIGENCE PIPELINE 🚀")
    print(f"🕒 Timestamp: {datetime.now().isoformat()}")
    print("=" * 80)

    start_time = time.time()
    
    successful_stages = 0
    total_enabled = len([s for s in PIPELINE_STAGES if s.get('enabled', True)])
    
    for i, stage in enumerate(PIPELINE_STAGES):
        if stage.get("enabled", True):
            if run_feature(stage):
                successful_stages += 1
            else:
                print(f"🛑 PIPELINE HALTED due to error in stage {i+1}: {stage['name']}")
                break
        else:
            print(f"⏭️  SKIPPING: {stage['name']} (disabled in config)")

    end_time = time.time()
    duration = end_time - start_time
    
    print("=" * 80)
    print("🏁 PIPELINE EXECUTION FINISHED 🏁")
    print(f"   Total Duration: {duration:.2f} seconds")
    print(f"   Stages Completed: {successful_stages} / {total_enabled}")
    print("=" * 80)

if __name__ == "__main__":
    # Before running, ensure the master virtual environment is activated
    if not hasattr(sys, 'real_prefix') and not (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix):
        print("\n⚠️ WARNING: You are not in a virtual environment.")
        print("Please activate the master_venv before running the pipeline:")
        print("  source master_venv/bin/activate")
        print("  python3 main_pipeline.py\n")
    
    main()
